#Read and Writing Data in Text Format

In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('ex1.csv') #sep=','
df

In [ ]:
pd.read_csv('ex2.csv')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [ ]:
pd.read_csv('ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
pd.read_csv('ex2.csv', names=['a', 'b', 'c', 'd', 'message'],index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [ ]:
#hierarchical index
parsed = pd.read_csv('csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [ ]:
result = pd.read_table('ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [ ]:
pd.read_csv('ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
result = pd.read_csv('ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [ ]:
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [ ]:
#How to show rows which having at least one null value ???

In [ ]:
#Set NA sentinels
sentinels = {'message': ['foo'], 'something': ['two']}
pd.read_csv('ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [1]:
import numpy as np

a = np.random.rand(10000,4)
a

key = np.array(['L','B','G','R','Q','H','E'])
b = np.random.randint(0,6,(10000,))

with open("ex6.txt","w") as f:
  for i in range(len(b)):
    f.write('\t'.join(["%.2f" % number for number in a[i]]) + '\t' + key[b][i]+"\n")

In [ ]:
pd.read_csv('ex6.csv', nrows=5, sep="\t")

In [2]:
chunker = pd.read_csv('ex6.csv', chunksize=1000,sep="\t")
chunker

In [ ]:
tot = pd.Series([])
for piece in chunker:
  tot = tot.add(piece['key'].value_counts(), fill_value=0)
tot = tot.sort_values(ascending=False)
tot

#Writing Data to Text Format

In [ ]:
data = pd.read_csv('ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [ ]:
data.to_csv('out.csv',sep=',')

In [ ]:
!cat out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [ ]:
data.to_csv('out.csv',sep=',',na_rep='NA')

In [ ]:
!cat out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,NA
1,two,5,6,NA,8,world
2,three,9,10,11.0,12,foo

In [ ]:
data.to_csv('out.csv', index=False, columns=['a', 'b', 'c'])
!cat out.csv

a,b,c
1,2,3.0
5,6,
9,10,11.0

#Json data

In [ ]:
obj = """
    {"name": "Wes",
     "places_lived": ["United States", "Spain", "Germany"],
     "pet": null,
     "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
                  {"name": "Katie", "age": 38,
                   "pets": ["Sixes", "Stache", "Cisco"]}]
} """

In [ ]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'pet': None,
 'places_lived': ['United States', 'Spain', 'Germany'],
 'siblings': [{'age': 30, 'name': 'Scott', 'pets': ['Zeus', 'Zuko']},
  {'age': 38, 'name': 'Katie', 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [ ]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  Scott   30
1  Katie   38

In [ ]:
data = pd.read_json('example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
print(data.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [ ]:
print(data.to_json(orient='records'))

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

#Pickle

To export data in binary format

In [4]:
frame = pd.read_csv('ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
frame.to_pickle('frame_pickle')

In [6]:
pd.read_pickle('frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

#Microsoft Excel Files

In [ ]:
xlsx = pd.ExcelFile('ex1.xlsx')
pd.read_excel(xlsx, 'sheet1')

     a     b     c     d message
0  1.0   2.0   3.0   4.0   hello
1  5.0   6.0   7.0   8.0   world
2  9.0  10.0  11.0  12.0     foo

In [ ]:
pd.read_excel('ex1.xlsx', 'sheet1')

     a     b     c     d message
0  1.0   2.0   3.0   4.0   hello
1  5.0   6.0   7.0   8.0   world
2  9.0  10.0  11.0  12.0     foo

In [ ]:
frame.to_excel('ex2.xlsx','sheet1')